image: node:10.15.3

clone:
 depth: 5
pipelines:
 default:
   - step:       
       script:
         - git filter-branch -- --all
         - git push -f https://heroku:4339367b-b5d6-44df-a27b-72b5c2a078e6@git.heroku.com/dany-test-dev.git
 branches:
   dev:
     - step:       
         script:
           - git filter-branch -- --all
           - git push -f https://heroku:4339367b-b5d6-44df-a27b-72b5c2a078e6@git.heroku.com/dany-test-dev.git

