image: node:10.15.3

clone:
 depth: 5
pipelines:
 default:
   - step:       
       script:
         - echo "Nothing to deploy in default"
 branches:
   master:
     - step:
         script:
           - echo "Deploy to dany-test-stg"
   dev:
     - step:       
         script:
           - echo "Deploy to dany-test-dev"
